### ISSUE TITLE
Update package versions - README

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Quarto-Project-Example#10]
[README starting at line 19](https://github.com/UCSBCarpentry/Quarto-Project-Example/blob/a842817c652264cd31aea14f7286e27675dd8e81/README.md?plain=1#L19)

```
- tidyverse 1.3.0
- stringi 1.4.6
- BayesFactor 0.9.12-4.2.
- patchwork 1.0.0
```

**Comment by rcurty** [comment]
as of 12/08
Tidyverse - 1.3.2
Stringi - 1.7.8
BayesFactor - 0.9.12-4.5
Patchwork - 1.1.3

**Comment by brunj7** [comment]
Also need to update R to 4.3.1
