### ISSUE TITLE
Delete files we won't use

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Quarto-Project-Example#2]
In episode 4 
remove /code/04-07 can be removed
data/  GARP-TEST mastersheet.xls ← retain
data/ bronars_sim ← retain
data/  removed all the other files in /data/
output/data/  keep
output/plots/  retain only…
heartrate.pdf
Bronars.pdf

**Comment by torwhite** [comment]
all done. 
Only differences:
removed output/plots/bronars.pdf because it isn't needed. and retained output/plots/hormones.pdf because it is needed.
