### ISSUE TITLE
missing CSV files

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Quarto-Project-Example#4]
Paul from Monash Univ. found following issue while conducting the workshop:

in file `code/01_data_preprocessing.R`
> `# Uncomment if libraries need to be loaded`
> `#library(tidyverse)`
> `#library(stringi)`
> `#source("analysis_scripts/functions/GARP_funcs.R")`

- No real need to leave these commented out. This script isn't intended to be sourced into a qmd.
- Incorrect path for `source()`.
- This script produces an error **because the CSV files are missing**.

I'm not sure if the files were removed to save space. It would be nice to have this working since it's part of demonstrating an end-to-end reproducible data analysis.

**Comment by torwhite** [comment]
Look into this more, this is a use case that is not part of the lesson as is. So we need to weigh the pros and cons of adding the files back in that we took out to simplify the example.

**Comment by torwhite** [comment]
Link to OSF more explicitly in instructor notes that if instructors want to use additional files they can be downloaded from OSF. Look at making this more explicit in the example readme as well.

**Comment by ilessing** [comment]
This has been addressed by updating the _extras/guides.md in the workshop repo.

https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/commit/9a0cf1c27b11e0489743170febdb3ea8a7d85621
