### ISSUE TITLE
Check - code/01_data_preprocessing.R

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/Quarto-Project-Example#5]
Are we using this code in any of the episodes? It looks like it was removed from the lesson.
Investigate if that is indeed an issue:

if (raw_data == "error")

"==" is a vector operation and "if" expects a single value. R might have become stricter about this in a recent version? I suggest using:

if (identical(raw_data, "error"))

**Comment by torwhite** [comment]
Although not used in the lesson,`code/01_data_preprocessing.R` should stay to allow for more ability to play with or test the example code.

**Comment by rcurty** [comment]
See #8

**Comment by rcurty** [comment]
we are keeping it as a good example to keep the code for processing data.
