### ISSUE TITLE
adjust for non-inclusion of Renv

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Quarto-Project-Example#6]
remove:
`source("renv/activate.R")`

from file: `.Rprofile`

see: [Oct 2022 commit‎](https://github.com/UCSBCarpentry/Quarto-Project-Example/blob/3662da0a7757616d660f8b2198ae714deb208a05/.Rprofile)

**Comment by torwhite** [comment]
Removed the .Rprofile because `source("renv/activate.R")` was all it contained.

**Comment by torwhite** [comment]
Please review @ilessing , @rcurty or @brunj7

**Comment by ilessing** [comment]
That's great.  thanks @torwhite
