### ISSUE TITLE
Review and update README with recent directory changes

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Quarto-Project-Example#8]
See #7

**Comment by brunj7** [comment]
- I updated the README according to the new file structure
- I updated the file paths in the RScripts to match the new file structure

One thing is I can not locate the `foodchoice_data` folder? @torwhite @rcurty is it supposed to be in this repo or downloaded from somewhere else?

**Comment by ilessing** [comment]
`foodchoice_budgetlines.csv` and other data was removed from the Example repo last Feb.

see: https://github.com/UCSBCarpentry/Quarto-Project-Example/commit/eb2e8a53f529a02795912097e944dd0b6396a359

**Comment by rcurty** [comment]
bring the file back after the workshop.

**Comment by rcurty** [comment]
The README mentions: Note: data/foodchoice_budgetlines.csv is not required to run analysis scripts but is for information only. However, this file is no longer part of the project example. Remove?

**Comment by rcurty** [comment]
the file was removed.
